### ISSUE TITLE
Unexpected value 'ngfModule' imported by the module 'LibraryModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by ronnyek** [AckerApple/angular-file#19] opened 2017-12-05 18:15 UTC
I just attempted to import this into a new angular-cli project and got the following error. I attempted to add ngfModule to imports in the module consuming. 
```
stateService.js:43 Error: Unexpected value 'ngfModule' imported by the module 'LibraryModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:466)
    at eval (compiler.js:15088)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15071)
    at JitCompiler._loadModules (compiler.js:33486)
    at JitCompiler._compileModuleAndComponents (compiler.js:33447)
    at JitCompiler.compileModuleAsync (compiler.js:33363)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:230)
    at eval (core.js:6441)
    at ZoneDelegate.invoke (zone.js:392)
```

**Comment by AckerApple** [comment] 2017-12-05 18:38
You must have Angular4 installed.

Just today we upgraded to Angular5 which does not work with Angular4

If you are stuck in Angular4, you will need to use the following command
```
npm install angular-file@0.3.8
```

**Comment by AckerApple** [comment] 2017-12-05 18:39
https://github.com/AckerApple/angular-file/issues/17

**Comment by AckerApple** [comment] 2017-12-05 18:41
Changed title to help other users find this issue report

Angular4 and 5 have incompatibilities

**Comment by ronnyek** [comment] 2017-12-05 19:07
I updated the project to angular 5.0.5 by deleting node_modules, updating packages.config and then install ```
+ @angular/platform-browser-dynamic@5.0.5
+ @angular/http@5.0.5
+ @angular/compiler-cli@5.0.5
+ @angular/forms@5.0.5
+ @angular/platform-browser@5.0.5
+ @angular/router@5.0.5
+ @angular/platform-server@5.0.5
+ @angular/animations@5.0.5
+ @angular/core@5.0.5
+ @angular/common@5.0.5
+ @angular/compiler@5.0.5
```

this isnt a just created angular/cli project, just the original 5.0.0 upgraded to 5.0.5, but still has the same problem. Maybe it's something else like tsconfigs

**Comment by AckerApple** [comment] 2017-12-05 19:11
Do you maybe also have a package-lock.json file that should have been deleted with node_modules (make sure both are deleted at the same time)? The package-lock.json file will keep you on previously installed dependency versions.

You can manually confirm you got the right version by opening ./node_modules/angular-file/package.json ... version 0.4.0 should be seen

I have already tried the upgrade in one project that was Angular4, got the error 100% like you got and now it's gone once everything updated.... Also check that you have the latest `@angular/cli` if you are using that.... Just make sure everything up to date.

In the end, please confirm if you are getting same exact error or a different error

**Comment by AckerApple** [comment] 2017-12-06 18:08
I am again facing this issue, again. Doing what I can and will report

**Comment by AckerApple** [comment] 2017-12-06 18:39
I have figured out the issue. Should be just another 20 minutes... I accidentally bundled this package with TypeScript 2.6.2 but Angular only works with 2.4.2 - 5

**Comment by AckerApple** [comment] 2017-12-06 18:51
Please install 0.4.1 .... Yup 0.4.0 is broken because I bundled with TypeScript 2.6.2 instead of 2.4.2

Confirmed working

**Comment by AckerApple** [comment] 2017-12-06 18:51
Please confirm and then close this issue

**Comment by AckerApple** [comment] 2017-12-08 12:48
I’m closing this issue. Reopen if needed.

Hope you’ve found this code useful so do please star it, follow me, or whatever free reputations points you could give would be greatly appreciated.

**Closed by AckerApple** 2017-12-08 12:48 UTC
Labels: question, ready to close
